name: New Issue
on:
  issues:
    types: [opened, reopened]
  workflow_dispatch:
  
env:
  ACTIONS_STEP_DEBUG: 1

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      id: add-label
      with:
        action: add
        issue-number: ${{ github.event.issue.number }}
        label-id: 'LA_kwDOIf586M8AAAABIGMImg'
        token: ${{ secrets.GITHUB_TOKEN }}
